service: serverless-etl

provider:
  name: google
  runtime: nodejs10
  region: us-east1
  project: etl-data-meetup
  # The GCF credentials can be a little tricky to set up. Luckily we've documented this for you here:
  # https://serverless.com/framework/docs/providers/google/guide/credentials/
  #
  # the path to the credentials file needs to be absolute
  credentials: ~/.gcloud/keyfile.json
  environment:
    RAW_STOCK_DATA_STORAGE: ${self:custom.rawStockDataStorage}
    PARSED_STOCK_DATA_STORAGE: ${self:custom.parsedStockDataStorage}
    STOCK_PIPELINE_QUEUE_NAME: ${self:custom.stockPipelineQueueName}
    BASE_URL: 'https://www.alphavantage.co/query'

plugins:
  - serverless-google-cloudfunctions

package:
  exclude:
    - node_modules/**
    - .gitignore
    - .git/**

custom:
  stockPipelineQueueName: stockPipelineQueue
  stockSelectorTriggerName: stockSelectorTrigger
  rawStockDataStorage: raw-stock-data-storage
  parsedStockDataStorage: parsed-stock-data-storage
  stockBigqueryDatasetName: stock_dataset
  stockBigqueryTableName: stock_table

functions:
  extractStockData:
    handler: extractStockData
    events:
      - event:
          eventType: providers/cloud.pubsub/eventTypes/topic.publish
          resource: projects/${self:provider.project}/topics/${self:custom.stockPipelineQueueName}

  stockSelector:
    handler: stockSelector
    events:
      - event:
          eventType: providers/cloud.pubsub/eventTypes/topic.publish
          resource: projects/${self:provider.project}/topics/${self:custom.stockSelectorTriggerName}
  
  transformStockData:
    handler: transformStockData
    events:
      - event:
          eventType: google.storage.object.finalize
          resource: projects/${self:provider.project}/buckets/${self:custom.rawStockDataStorage}

resources:
  resources:
    # GCS
    - name: ${self:custom.rawStockDataStorage}
      type: storage.v1.bucket
      properties:
        project: ${self:provider.project}
        name: ${self:custom.rawStockDataStorage}
        lifecycle:
          rule:
          - action:
              type: Delete
            condition:
              age: 5
    - name: ${self:custom.parsedStockDataStorage}
      type: storage.v1.bucket
      properties:
        project: ${self:provider.project}
        name: ${self:custom.parsedStockDataStorage}

    # PubSub
    - name: ${self:custom.stockPipelineQueueName}
      type: pubsub.v1.topic
      properties:
        topic: ${self:custom.stockPipelineQueueName}
    - name: ${self:custom.stockSelectorTriggerName}
      type: pubsub.v1.topic
      properties:
        topic: ${self:custom.stockSelectorTriggerName}
    
    # Bigquery
    - name: ${self:custom.stockBigqueryDatasetName}
      type: bigquery.v2.dataset
      properties:
        name: ${self:custom.stockBigqueryDatasetName}
        datasetReference:
          datasetId: ${self:custom.stockBigqueryDatasetName}
    - name: ${self:custom.stockBigqueryTableName}
      type: bigquery.v2.table
      properties:
        tableReference:
          tableId: ${self:custom.stockBigqueryTableName}
        name: ${self:custom.stockBigqueryTableName}
        datasetId: $(ref.${self:custom.stockBigqueryDatasetName}.datasetReference.datasetId)
        schema:
          fields:
            - name: date
              type: DATE
            - name: symbol
              type: STRING
            - name: open
              type: NUMERIC
            - name: close
              type: NUMERIC
            - name: low
              type: NUMERIC
            - name: high
              type: NUMERIC
            - name: volume
              type: NUMERIC
            - name: extracted_at
              type: TIMESTAMP
            - name: transformed_at
              type: TIMESTAMP
            - name: tick
              type: STRING
        timePartitioning:
          type: DAY
          field: date
        clustering:
          fields: 
            - symbol
